#!/usr/bin/env python
# xCOM - a Simple Component Framework
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Library General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Library General Public License for more details.
#
# You should have received a copy of the GNU Library General Public
# License along with this library; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.

import sys;
import optparse;

from codegen import parser;

def xc_codegen_main():

   # Create parser for option arguments
   opt_parser = optparse.OptionParser ('%prog [options] files...');
   # TODO add options here

   # Parse command line
   (opts, args) = opt_parser.parse_args ();

   # Parse supplied XML files
   for path in args:
      fd  = open (path);
      xmlData = fd.read ();
      fd.close ();
      parser.parse (path, xmlData);

   print '# main()';

if __name__ == "__main__":
    xc_codegen_main ();

